version: '3'
services:
  backend:
    build: ./mogonet
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
